#ifndef _LWP_C_
#define _LWP_C_
int create_lwp(unsigned long stack_size,int (*fun)(void *),void *arg);
asm "@create_lwp"
asm "push %rdi"
asm "push %rsi"
asm "push %rdx"
asm "push %r10"
asm "push %r8"
asm "push %r9"
asm "push %r11"
asm "push %r12"
asm "push %r13"
asm "push %r14"
asm "mov 88(%rsp),%rsi"
asm "xor %edi,%edi"
asm "mov $3,%edx"
asm "mov $0x22,%r10d"
asm "mov %edi,%r8d"
asm "mov %edi,%r9d"
asm "dec %r8"
asm "mov $9,%eax"
asm "syscall"
asm "cmp $0xfffffffffffff000,%rax"
asm "ja @_create_lwp_end"
asm "mov 88(%rsp),%r12"
asm "mov 96(%rsp),%rdx"
asm "mov 104(%rsp),%r14"
asm "mov $0x18f00,%edi"
asm "mov %rax,%r13"
asm "lea (%rax,%r12),%rsi"
asm "mov $56,%eax"
asm "syscall"
asm "cmp $0xfffffffffffff000,%rax"
asm "ja @_create_lwp_err"

asm "test %rax,%rax"
asm "jne @_create_lwp_end"
asm "push %r12"
asm "push %r14"
asm "call *%rdx"
asm "mov 8(%rsp),%rsi"
asm "lea 16(%rsp),%rdi"
asm "sub %rsi,%rdi"
asm "mov %rax,%rdx"
asm "mov $11,%eax"
asm "syscall"
asm "mov %rdx,%rdi"
asm "mov $60,%eax"
asm "syscall"

asm "@_create_lwp_err"
asm "mov %r12,%rsi"
asm "mov %r13,%rdi"
asm "mov $11,%eax"
asm "syscall"

asm "@_create_lwp_end"
asm "pop %r14"
asm "pop %r13"
asm "pop %r12"
asm "pop %r11"
asm "pop %r9"
asm "pop %r8"
asm "pop %r10"
asm "pop %rdx"
asm "pop %rsi"
asm "pop %rdi"
asm "ret"
#endif
